# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bucka\Desktop\VS code\Python\Kryptologie\ADFGVX_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 693)
        MainWindow.setStyleSheet("background-color: rgb(69, 4, 3);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelPlainText = QtWidgets.QLabel(self.centralwidget)
        self.labelPlainText.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelPlainText.setObjectName("labelPlainText")
        self.verticalLayout_2.addWidget(self.labelPlainText)
        self.labelKey = QtWidgets.QLabel(self.centralwidget)
        self.labelKey.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelKey.setObjectName("labelKey")
        self.verticalLayout_2.addWidget(self.labelKey)
        self.labelEncryptedText = QtWidgets.QLabel(self.centralwidget)
        self.labelEncryptedText.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelEncryptedText.setObjectName("labelEncryptedText")
        self.verticalLayout_2.addWidget(self.labelEncryptedText)
        self.labelDecryptedText = QtWidgets.QLabel(self.centralwidget)
        self.labelDecryptedText.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelDecryptedText.setObjectName("labelDecryptedText")
        self.verticalLayout_2.addWidget(self.labelDecryptedText)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditPlainText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPlainText.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditPlainText.setText("")
        self.lineEditPlainText.setClearButtonEnabled(False)
        self.lineEditPlainText.setObjectName("lineEditPlainText")
        self.verticalLayout.addWidget(self.lineEditPlainText)
        self.lineEditKey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditKey.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditKey.setObjectName("lineEditKey")
        self.verticalLayout.addWidget(self.lineEditKey)
        self.lineEditEncryptedText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEncryptedText.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditEncryptedText.setObjectName("lineEditEncryptedText")
        self.verticalLayout.addWidget(self.lineEditEncryptedText)
        self.lineEditDecryptedText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDecryptedText.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditDecryptedText.setObjectName("lineEditDecryptedText")
        self.verticalLayout.addWidget(self.lineEditDecryptedText)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButtonEncrypt = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonEncrypt.setChecked(True)
        self.radioButtonEncrypt.setObjectName("radioButtonEncrypt")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonEncrypt)
        self.verticalLayout_3.addWidget(self.radioButtonEncrypt)
        self.radioButtonDecrypt = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonDecrypt.setChecked(False)
        self.radioButtonDecrypt.setObjectName("radioButtonDecrypt")
        self.buttonGroup.addButton(self.radioButtonDecrypt)
        self.verticalLayout_3.addWidget(self.radioButtonDecrypt)
        self.pushButtonRUN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRUN.setStyleSheet("QPushButton{\n"
"border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(88, 181, 124);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(118, 131, 124);\n"
"}")
        self.pushButtonRUN.setObjectName("pushButtonRUN")
        self.verticalLayout_3.addWidget(self.pushButtonRUN)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.lineEditError = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditError.setStyleSheet("border-radius:2px;\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 55, 55);")
        self.lineEditError.setText("")
        self.lineEditError.setReadOnly(True)
        self.lineEditError.setObjectName("lineEditError")
        self.verticalLayout_4.addWidget(self.lineEditError)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelSanitizedText = QtWidgets.QLabel(self.centralwidget)
        self.labelSanitizedText.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelSanitizedText.setObjectName("labelSanitizedText")
        self.verticalLayout_6.addWidget(self.labelSanitizedText)
        self.labelSanitizedKey = QtWidgets.QLabel(self.centralwidget)
        self.labelSanitizedKey.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelSanitizedKey.setObjectName("labelSanitizedKey")
        self.verticalLayout_6.addWidget(self.labelSanitizedKey)
        spacerItem = QtWidgets.QSpacerItem(20, 117, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEditSanitizedText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSanitizedText.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditSanitizedText.setReadOnly(True)
        self.lineEditSanitizedText.setObjectName("lineEditSanitizedText")
        self.verticalLayout_7.addWidget(self.lineEditSanitizedText)
        self.lineEditSanitizedKey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSanitizedKey.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditSanitizedKey.setReadOnly(True)
        self.lineEditSanitizedKey.setObjectName("lineEditSanitizedKey")
        self.verticalLayout_7.addWidget(self.lineEditSanitizedKey)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelPlainTextCipherTable = QtWidgets.QLabel(self.centralwidget)
        self.labelPlainTextCipherTable.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelPlainTextCipherTable.setObjectName("labelPlainTextCipherTable")
        self.horizontalLayout_3.addWidget(self.labelPlainTextCipherTable)
        self.radioButton5x5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton5x5.setObjectName("radioButton5x5")
        self.horizontalLayout_3.addWidget(self.radioButton5x5)
        self.radioButton6x6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton6x6.setChecked(True)
        self.radioButton6x6.setObjectName("radioButton6x6")
        self.horizontalLayout_3.addWidget(self.radioButton6x6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelPlainText_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelPlainText_4.setStyleSheet("font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.labelPlainText_4.setObjectName("labelPlainText_4")
        self.horizontalLayout_5.addWidget(self.labelPlainText_4)
        self.lineEditTableSeed = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTableSeed.setStyleSheet("border-radius:2px;\n"
"background-color:rgb(88, 111, 124);\n"
"font:87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lineEditTableSeed.setObjectName("lineEditTableSeed")
        self.horizontalLayout_5.addWidget(self.lineEditTableSeed)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tableWidgetCipherTable = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetCipherTable.setStyleSheet("QHeaderView::section {\n"
"    background-color:rgb(88, 111, 124);\n"
"    color: white; \n"
"    font-weight: bold;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    height: 18px\n"
"\n"
"}\n"
"QHeaderView::section {\n"
"padding: 4px;\n"
"}\n"
"QTableWidget{\n"
"background-color: rgb(69, 4, 3);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.tableWidgetCipherTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCipherTable.setObjectName("tableWidgetCipherTable")
        self.tableWidgetCipherTable.setColumnCount(6)
        self.tableWidgetCipherTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCipherTable.setItem(0, 0, item)
        self.tableWidgetCipherTable.horizontalHeader().setDefaultSectionSize(68)
        self.tableWidgetCipherTable.horizontalHeader().setHighlightSections(True)
        self.tableWidgetCipherTable.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetCipherTable.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetCipherTable.verticalHeader().setVisible(True)
        self.tableWidgetCipherTable.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCipherTable.verticalHeader().setDefaultSectionSize(30)
        self.tableWidgetCipherTable.verticalHeader().setMinimumSectionSize(25)
        self.tableWidgetCipherTable.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetCipherTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tableWidgetCipherTable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelTranspositionTable = QtWidgets.QLabel(self.centralwidget)
        self.labelTranspositionTable.setObjectName("labelTranspositionTable")
        self.verticalLayout_8.addWidget(self.labelTranspositionTable)
        self.tableWidgetTranspositionTable = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetTranspositionTable.setStyleSheet("QHeaderView::section {\n"
"    background-color:rgb(88, 111, 124);\n"
"    color: white; \n"
"    font-weight: bold;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    height: 18px\n"
"\n"
"}\n"
"QHeaderView::section {\n"
"padding: 4px;\n"
"}\n"
"QTableWidget{\n"
"background-color: rgb(69, 4, 3);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.tableWidgetTranspositionTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetTranspositionTable.setObjectName("tableWidgetTranspositionTable")
        self.tableWidgetTranspositionTable.setColumnCount(0)
        self.tableWidgetTranspositionTable.setRowCount(0)
        self.tableWidgetTranspositionTable.horizontalHeader().setDefaultSectionSize(68)
        self.tableWidgetTranspositionTable.horizontalHeader().setHighlightSections(True)
        self.tableWidgetTranspositionTable.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetTranspositionTable.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetTranspositionTable.verticalHeader().setVisible(True)
        self.tableWidgetTranspositionTable.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetTranspositionTable.verticalHeader().setDefaultSectionSize(30)
        self.tableWidgetTranspositionTable.verticalHeader().setMinimumSectionSize(25)
        self.tableWidgetTranspositionTable.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetTranspositionTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.tableWidgetTranspositionTable)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelTranspositionTableAlphabetically = QtWidgets.QLabel(self.centralwidget)
        self.labelTranspositionTableAlphabetically.setObjectName("labelTranspositionTableAlphabetically")
        self.verticalLayout_9.addWidget(self.labelTranspositionTableAlphabetically)
        self.tableWidgetTranspositionTableAlphabetically = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetTranspositionTableAlphabetically.setStyleSheet("QHeaderView::section {\n"
"    background-color:rgb(88, 111, 124);\n"
"    color: white; \n"
"    font-weight: bold;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    height: 18px\n"
"\n"
"}\n"
"QHeaderView::section {\n"
"padding: 4px;\n"
"}\n"
"QTableWidget{\n"
"background-color: rgb(69, 4, 3);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.tableWidgetTranspositionTableAlphabetically.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetTranspositionTableAlphabetically.setObjectName("tableWidgetTranspositionTableAlphabetically")
        self.tableWidgetTranspositionTableAlphabetically.setColumnCount(0)
        self.tableWidgetTranspositionTableAlphabetically.setRowCount(0)
        self.tableWidgetTranspositionTableAlphabetically.horizontalHeader().setDefaultSectionSize(68)
        self.tableWidgetTranspositionTableAlphabetically.horizontalHeader().setHighlightSections(True)
        self.tableWidgetTranspositionTableAlphabetically.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetTranspositionTableAlphabetically.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetTranspositionTableAlphabetically.verticalHeader().setVisible(True)
        self.tableWidgetTranspositionTableAlphabetically.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetTranspositionTableAlphabetically.verticalHeader().setDefaultSectionSize(30)
        self.tableWidgetTranspositionTableAlphabetically.verticalHeader().setMinimumSectionSize(25)
        self.tableWidgetTranspositionTableAlphabetically.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetTranspositionTableAlphabetically.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.tableWidgetTranspositionTableAlphabetically)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPlainText.setText(_translate("MainWindow", "Plain Text"))
        self.labelKey.setText(_translate("MainWindow", "Key"))
        self.labelEncryptedText.setText(_translate("MainWindow", "Encrypted Text"))
        self.labelDecryptedText.setText(_translate("MainWindow", "Decrypted Text"))
        self.lineEditKey.setPlaceholderText(_translate("MainWindow", "Minumum key lenght is 5"))
        self.radioButtonEncrypt.setText(_translate("MainWindow", "ENCRYPT"))
        self.radioButtonDecrypt.setText(_translate("MainWindow", "DECRYPT             "))
        self.pushButtonRUN.setText(_translate("MainWindow", "RUN"))
        self.labelSanitizedText.setText(_translate("MainWindow", "Sanitized Text"))
        self.labelSanitizedKey.setText(_translate("MainWindow", "Sanitized Key"))
        self.labelPlainTextCipherTable.setText(_translate("MainWindow", "Cipher Table"))
        self.radioButton5x5.setText(_translate("MainWindow", "5x5"))
        self.radioButton6x6.setText(_translate("MainWindow", "6x6"))
        self.labelPlainText_4.setText(_translate("MainWindow", "Table Seed"))
        item = self.tableWidgetCipherTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidgetCipherTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.tableWidgetCipherTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "F"))
        item = self.tableWidgetCipherTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "G"))
        item = self.tableWidgetCipherTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "V"))
        item = self.tableWidgetCipherTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidgetCipherTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidgetCipherTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D"))
        item = self.tableWidgetCipherTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "F"))
        item = self.tableWidgetCipherTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "G"))
        item = self.tableWidgetCipherTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "V"))
        item = self.tableWidgetCipherTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "X"))
        __sortingEnabled = self.tableWidgetCipherTable.isSortingEnabled()
        self.tableWidgetCipherTable.setSortingEnabled(False)
        self.tableWidgetCipherTable.setSortingEnabled(__sortingEnabled)
        self.labelTranspositionTable.setText(_translate("MainWindow", "Transposition Table"))
        self.labelTranspositionTableAlphabetically.setText(_translate("MainWindow", "Transposition Table Alphabetically"))
