# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bucka\Documents\GitHub\School\Simon\Kryptologie\RSA\RSA1Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 643)
        MainWindow.setStyleSheet("background-color: rgb(78, 65, 135);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelText = QtWidgets.QLabel(self.centralwidget)
        self.labelText.setMaximumSize(QtCore.QSize(16777215, 28))
        self.labelText.setObjectName("labelText")
        self.verticalLayout_6.addWidget(self.labelText)
        self.textEditTextToEncrypt = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditTextToEncrypt.setMaximumSize(QtCore.QSize(16777215, 125))
        self.textEditTextToEncrypt.setStyleSheet("background-color: rgb(48, 131, 220);\n"
"")
        self.textEditTextToEncrypt.setObjectName("textEditTextToEncrypt")
        self.verticalLayout_6.addWidget(self.textEditTextToEncrypt)
        self.labelText_6 = QtWidgets.QLabel(self.centralwidget)
        self.labelText_6.setObjectName("labelText_6")
        self.verticalLayout_6.addWidget(self.labelText_6)
        self.textEditNumeralRepresentation = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditNumeralRepresentation.setMaximumSize(QtCore.QSize(16777215, 125))
        self.textEditNumeralRepresentation.setStyleSheet("background-color: rgb(48, 131, 220);\n"
"")
        self.textEditNumeralRepresentation.setObjectName("textEditNumeralRepresentation")
        self.verticalLayout_6.addWidget(self.textEditNumeralRepresentation)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelN_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelN_3.setObjectName("labelN_3")
        self.verticalLayout_5.addWidget(self.labelN_3)
        self.labelE_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelE_3.setObjectName("labelE_3")
        self.verticalLayout_5.addWidget(self.labelE_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditNEncrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNEncrypt.setObjectName("lineEditNEncrypt")
        self.verticalLayout_4.addWidget(self.lineEditNEncrypt)
        self.lineEditEEncrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEEncrypt.setObjectName("lineEditEEncrypt")
        self.verticalLayout_4.addWidget(self.lineEditEEncrypt)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.labelText_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelText_3.setObjectName("labelText_3")
        self.verticalLayout_6.addWidget(self.labelText_3)
        self.textEditEncrypted = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEncrypted.setMaximumSize(QtCore.QSize(16777215, 125))
        self.textEditEncrypted.setStyleSheet("background-color: rgb(48, 131, 220);\n"
"")
        self.textEditEncrypted.setObjectName("textEditEncrypted")
        self.verticalLayout_6.addWidget(self.textEditEncrypted)
        self.pushButtonEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEncrypt.setStyleSheet("QPushButton{\n"
"background-color: rgb(78, 65, 135);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(48, 131, 220);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(48, 181, 220);\n"
"}\n"
"")
        self.pushButtonEncrypt.setObjectName("pushButtonEncrypt")
        self.verticalLayout_6.addWidget(self.pushButtonEncrypt)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelLenghtOfPrimeNumber = QtWidgets.QLabel(self.centralwidget)
        self.labelLenghtOfPrimeNumber.setObjectName("labelLenghtOfPrimeNumber")
        self.verticalLayout_3.addWidget(self.labelLenghtOfPrimeNumber)
        self.lineEditLenghtOfPrimeNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLenghtOfPrimeNumber.setMaxLength(10)
        self.lineEditLenghtOfPrimeNumber.setObjectName("lineEditLenghtOfPrimeNumber")
        self.verticalLayout_3.addWidget(self.lineEditLenghtOfPrimeNumber)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Jednotky = QtWidgets.QVBoxLayout()
        self.Jednotky.setObjectName("Jednotky")
        self.labelP = QtWidgets.QLabel(self.centralwidget)
        self.labelP.setObjectName("labelP")
        self.Jednotky.addWidget(self.labelP)
        self.labelQ = QtWidgets.QLabel(self.centralwidget)
        self.labelQ.setObjectName("labelQ")
        self.Jednotky.addWidget(self.labelQ)
        self.labelPhi = QtWidgets.QLabel(self.centralwidget)
        self.labelPhi.setObjectName("labelPhi")
        self.Jednotky.addWidget(self.labelPhi)
        self.labelN = QtWidgets.QLabel(self.centralwidget)
        self.labelN.setObjectName("labelN")
        self.Jednotky.addWidget(self.labelN)
        self.labelE = QtWidgets.QLabel(self.centralwidget)
        self.labelE.setObjectName("labelE")
        self.Jednotky.addWidget(self.labelE)
        self.labelD = QtWidgets.QLabel(self.centralwidget)
        self.labelD.setObjectName("labelD")
        self.Jednotky.addWidget(self.labelD)
        self.horizontalLayout.addLayout(self.Jednotky)
        self.JednotkyLine = QtWidgets.QWidget(self.centralwidget)
        self.JednotkyLine.setStyleSheet("font:87 8pt \"Arial Black\";\n"
"")
        self.JednotkyLine.setObjectName("JednotkyLine")
        self.gridLayout = QtWidgets.QGridLayout(self.JednotkyLine)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lineEditN = QtWidgets.QLineEdit(self.JednotkyLine)
        self.lineEditN.setObjectName("lineEditN")
        self.gridLayout.addWidget(self.lineEditN, 6, 0, 1, 1)
        self.lineEditP = QtWidgets.QLineEdit(self.JednotkyLine)
        self.lineEditP.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditP.setObjectName("lineEditP")
        self.gridLayout.addWidget(self.lineEditP, 0, 0, 1, 1)
        self.lineEditQ = QtWidgets.QLineEdit(self.JednotkyLine)
        self.lineEditQ.setObjectName("lineEditQ")
        self.gridLayout.addWidget(self.lineEditQ, 2, 0, 1, 1)
        self.lineEditPhi = QtWidgets.QLineEdit(self.JednotkyLine)
        self.lineEditPhi.setObjectName("lineEditPhi")
        self.gridLayout.addWidget(self.lineEditPhi, 4, 0, 1, 1)
        self.lineEditE = QtWidgets.QLineEdit(self.JednotkyLine)
        self.lineEditE.setObjectName("lineEditE")
        self.gridLayout.addWidget(self.lineEditE, 8, 0, 1, 1)
        self.lineEditD = QtWidgets.QLineEdit(self.JednotkyLine)
        self.lineEditD.setObjectName("lineEditD")
        self.gridLayout.addWidget(self.lineEditD, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        self.horizontalLayout.addWidget(self.JednotkyLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButtonGenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGenerateKeys.setStyleSheet("QPushButton{\n"
"background-color: rgb(78, 65, 135);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(48, 131, 220);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(48, 181, 220);\n"
"}\n"
"")
        self.pushButtonGenerateKeys.setObjectName("pushButtonGenerateKeys")
        self.verticalLayout.addWidget(self.pushButtonGenerateKeys)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelText_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelText_4.setMaximumSize(QtCore.QSize(16777215, 28))
        self.labelText_4.setObjectName("labelText_4")
        self.horizontalLayout_3.addWidget(self.labelText_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.textEditEncrypted_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEncrypted_2.setMaximumSize(QtCore.QSize(16777215, 125))
        self.textEditEncrypted_2.setStyleSheet("background-color: rgb(48, 131, 220);\n"
"")
        self.textEditEncrypted_2.setObjectName("textEditEncrypted_2")
        self.verticalLayout_9.addWidget(self.textEditEncrypted_2)
        self.labelText_7 = QtWidgets.QLabel(self.centralwidget)
        self.labelText_7.setObjectName("labelText_7")
        self.verticalLayout_9.addWidget(self.labelText_7)
        self.textEditNumeralRepresentation_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditNumeralRepresentation_2.setMaximumSize(QtCore.QSize(16777215, 125))
        self.textEditNumeralRepresentation_2.setStyleSheet("background-color: rgb(48, 131, 220);\n"
"")
        self.textEditNumeralRepresentation_2.setObjectName("textEditNumeralRepresentation_2")
        self.verticalLayout_9.addWidget(self.textEditNumeralRepresentation_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelN_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelN_4.setObjectName("labelN_4")
        self.verticalLayout_8.addWidget(self.labelN_4)
        self.labelD_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelD_3.setObjectName("labelD_3")
        self.verticalLayout_8.addWidget(self.labelD_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEditNDecrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNDecrypt.setObjectName("lineEditNDecrypt")
        self.verticalLayout_7.addWidget(self.lineEditNDecrypt)
        self.lineEditDDecrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDDecrypt.setObjectName("lineEditDDecrypt")
        self.verticalLayout_7.addWidget(self.lineEditDDecrypt)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.labelText_5 = QtWidgets.QLabel(self.centralwidget)
        self.labelText_5.setObjectName("labelText_5")
        self.verticalLayout_9.addWidget(self.labelText_5)
        self.textEditDecrypted = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditDecrypted.setMaximumSize(QtCore.QSize(16777215, 125))
        self.textEditDecrypted.setStyleSheet("background-color: rgb(48, 131, 220);\n"
"")
        self.textEditDecrypted.setObjectName("textEditDecrypted")
        self.verticalLayout_9.addWidget(self.textEditDecrypted)
        self.pushButtonDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDecrypt.setStyleSheet("QPushButton{\n"
"background-color: rgb(78, 65, 135);\n"
"font:87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(48, 131, 220);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(48, 181, 220);\n"
"}\n"
"")
        self.pushButtonDecrypt.setObjectName("pushButtonDecrypt")
        self.verticalLayout_9.addWidget(self.pushButtonDecrypt)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"background-color: rgb(48, 131, 220);\n"
"    color: white; \n"
"    font-weight: bold;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"    height: 18px\n"
"\n"
"}\n"
"QHeaderView::section {\n"
"padding: 4px;\n"
"}\n"
"QTableWidget{\n"
"font:87 12pt \"Arial Black\";\n"
"}")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelText.setText(_translate("MainWindow", "Text to Encrypt"))
        self.textEditTextToEncrypt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:80; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ahoj</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.labelText_6.setText(_translate("MainWindow", "Numeral Representation"))
        self.labelN_3.setText(_translate("MainWindow", "N:"))
        self.labelE_3.setText(_translate("MainWindow", "E:"))
        self.labelText_3.setText(_translate("MainWindow", "Encrypted Text"))
        self.pushButtonEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.labelLenghtOfPrimeNumber.setText(_translate("MainWindow", "Lenght of prime number"))
        self.lineEditLenghtOfPrimeNumber.setText(_translate("MainWindow", "10"))
        self.labelP.setText(_translate("MainWindow", "p:"))
        self.labelQ.setText(_translate("MainWindow", "q:"))
        self.labelPhi.setText(_translate("MainWindow", "Phi:"))
        self.labelN.setText(_translate("MainWindow", "N:"))
        self.labelE.setText(_translate("MainWindow", "E:"))
        self.labelD.setText(_translate("MainWindow", "D:"))
        self.pushButtonGenerateKeys.setText(_translate("MainWindow", "Generate keys"))
        self.labelText_4.setText(_translate("MainWindow", "Encrypted Text"))
        self.labelText_7.setText(_translate("MainWindow", "Numeral Representation"))
        self.labelN_4.setText(_translate("MainWindow", "N:"))
        self.labelD_3.setText(_translate("MainWindow", "D:"))
        self.labelText_5.setText(_translate("MainWindow", "Decrypted Text"))
        self.pushButtonDecrypt.setText(_translate("MainWindow", "Decrypt"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Char"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ASCII"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Binary"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Block of 4 characters"))
